Skip to content
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.

tor onion sdk
Repositories
Code7K
Commits2
Issues18
Marketplace
Topics
Wikis226
Users
Language

Sort

7,479 code results
@PaasmerIoT
PaasmerIoT/ION-TOR-SDK – README.md
Showing the top six matches
Last indexed on Jul 8, 2018
Markdown
# ION-TOR SDK for Single Board Computers Running Linux

## Overview

The ION-TOR SDK for Single Board Computers (SBC) like Raspberry-PI, Intel Edison, Beagle Bone is a collection of source files that enables you to connect to the ION-TOR service. It includes the tor libraries to connect to TOR network. It is distributed in the application form and intended to be built into customer solution along with other libraries.

## Features

The ION-TOR-SDK simplifies access to the TOR network and automatically configures a .onion **DNS** name along with a hidden service for accessing a UI on a TOR browser.
@HafeezRai
HafeezRai/decenterlizedbtc – README.md
Showing the top five matches
Last indexed on Jul 11, 2018
Markdown
This is a fork of [Thali Project](http://www.thaliproject.org/)'s [Tor_Onion_Proxy_Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library).<br>
__What__: Enable Android and Java applications to easily host their own Tor Onion Proxies using the core Tor binaries. Just by including an AAR or JAR an app can launch and manage the Tor OP as well as start a hidden service.
@sakazz
sakazz/exchange – README.md
Showing the top five matches
Last indexed on Jul 10, 2018
Markdown
This is a fork of [Thali Project](http://www.thaliproject.org/)'s [Tor_Onion_Proxy_Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library).<br>
__What__: Enable Android and Java applications to easily host their own Tor Onion Proxies using the core Tor binaries. Just by including an AAR or JAR an app can launch and manage the Tor OP as well as start a hidden service.
@codigopublico
codigopublico/Git – README.md
Showing the top five matches
Last indexed on Jul 10, 2018
Markdown
This is a fork of [Thali Project](http://www.thaliproject.org/)'s [Tor_Onion_Proxy_Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library).<br>
__What__: Enable Android and Java applications to easily host their own Tor Onion Proxies using the core Tor binaries. Just by including an AAR or JAR an app can launch and manage the Tor OP as well as start a hidden service.
@lordzouga
lordzouga/torandroidlib – README.md
Showing the top four matches
Last indexed on Jul 13, 2018
Markdown
Tor_Onion_Proxy_Library
=======================
NOTE: This project exists independently of the Tor Project.

__What__: Enable Android and Java applications to easily host their own Tor Onion Proxies using the core Tor binaries. Just by including an AAR or JAR an app can launch and manage the Tor OP as well as start a hidden service.
@elkingtowa
elkingtowa/cloak – README.markdown
Showing the top five matches
Last indexed on Jun 28, 2018
Markdown
---

* **OnionBrowser**: 1.5.3 (20140630.1) — [See changelog][changelog]
* **[Tor][tor]**: 0.2.4.22 (May 16 2014)
[miketigas]: https://mike.tig.as/
[license]: https://github.com/mtigas/iOS-OnionBrowser/blob/master/LICENSE
[tor]: https://www.torproject.org/
@dabertram
dabertram/android_sdk_test – variablesAndContainers.dat
Showing the top match
Last indexed on Jun 27, 2018
ImePreferences-com.android.ide.eclipse.adt.ANDROID_FRAMEWORK^C:/Users/David/Desktop/adt-bundle-windows-x86_64-20130729/sdk/platforms/android-18/android.jarEC:/Users/David/Desktop/adt-bundle-windows-x86_64-20130729/sdk/sources3com/android/internal/**javadoc_location'http://developer.android.com/reference/%com.android.ide.eclipse.adt.LIBRARIES(com.android.ide.eclipse.adt.DEPENDENCIES	
@elkingtowa
elkingtowa/cloak – project.pbxproj
Showing the top three matches
Last indexed on Jun 28, 2018
		6937425B189CC514002C65A0 /* NJKWebViewProgressView.m in Sources */ = {isa = PBXBuildFile; fileRef = 69374259189CC514002C65A0 /* NJKWebViewProgressView.m */; };
		6940BD1F15F84C0C00FE74CB /* TorController.m in Sources */ = {isa = PBXBuildFile; fileRef = 6940BD1E15F84C0C00FE74CB /* TorController.m */; };
				696F9EB114F8DD5300BC5FDC /* ThirdParty */,
				69BB0A4C14F8D31800E7E909 /* Tor */,
				696EBD7D14F7877900B81BC9 /* OnionBrowser */,
@ymmah
ymmah/bitsquare – README.md
Showing the top five matches
Last indexed on Jul 9, 2018
Markdown
This is a fork of [Thali Project](http://www.thaliproject.org/)'s [Tor_Onion_Proxy_Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library).<br>
__What__: Enable Android and Java applications to easily host their own Tor Onion Proxies using the core Tor binaries. Just by including an AAR or JAR an app can launch and manage the Tor OP as well as start a hidden service.
@onionApps
onionApps/ourbook – Tor.java
Showing the top three matches
Last indexed on Jul 2, 2018
Java
/*
 * Network.onion - fully distributed p2p social network using onion routing
 *
 * http://play.google.com/store/apps/details?id=onion.network
 * http://onionapps.github.io/Network.onion/
 * http://github.com/onionApps/Network.onion
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
